Webbank/widget data
quadpay/quadpay-merchant-sdk-android pull request #11
Opened 2023-04-21 10:48 UTC by PetrosZip

https://quadpay.atlassian.net/browse/CKO-2495

2023-04-24 14:44 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/WidgetDataApi.java
> +    Call<WidgetData> getWidgetData(
Done

2023-04-24 15:58 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/QuadPayPaymentWidget.java
> +            Retrofit retrofit = new Retrofit.Builder()
Done

2023-04-25 09:17 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/QuadPayPaymentWidget.java
> +        PaymentWidgetHeader paymentWidgetHeader = new PaymentWidgetHeader(context, null,learnMoreUrl,isMFPPMerchant,minModal, applyGrayLabel);
oh didnt realise let me fix it

2023-04-26 12:31 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/QuadPayPaymentWidget.java
> +                    amount = String.valueOf((Float.parseFloat(amount)+ maxFee));
Done

2023-04-28 11:40 UTC, rhyswilliamszip requested changes
One additional point, if a merchant was using our library and a customer viewed both the widget and then payment widget throughout their journey, customer fees will be fetched twice.

It would be better to cache this data so that if we've fetched once it's available for the lifetime of the application, or as long as we believe a checkout will happen for.

Example code below (I tested this myself and didn't get any issues)
```
public class GatewayClient {
    private static GatewayClient instance = null;
    private final GatewayApi gatewayApi;

    private GatewayClient(Context context){
        Cache cache = this.httpCache(context);
        Retrofit retrofit = new Retrofit.Builder().baseUrl(BuildConfig.GatewayUrl)
                .addConverterFactory(GsonConverterFactory.create())
                .client(okHttp(cache))
                .build();
        this.gatewayApi = retrofit.create(GatewayApi.class);
    }

    private OkHttpClient okHttp(Cache cache) {
        return new OkHttpClient.Builder()
                .cache(cache)
                .addNetworkInterceptor(new CacheInterceptor())
                .build();
    }

    private Cache httpCache(Context applicationContext) {
        long CACHE_SIZE = 5 * 1024 * 1024L;
        File httpCacheDirectory = new File(applicationContext.getCacheDir(), "zip-http-cache");
        return new Cache(httpCacheDirectory, CACHE_SIZE);
    }

    public static synchronized GatewayClient getInstance(Context context){
        if (instance == null) {
            instance = new GatewayClient(context);
        }
        return instance;
    }

    public GatewayApi getWidgetDataApi() {
        return gatewayApi;
    }
}
...public class CacheInterceptor implements Interceptor {
    @NonNull
    @Override
    public Response intercept(Chain chain) throws IOException {
        Response response = chain.proceed(chain.request());

        CacheControl cacheControl = new CacheControl.Builder()
                .maxAge(30, TimeUnit.MINUTES) // 30 minutes cache
                .build();

        return response.newBuilder()
                .removeHeader("Pragma")
                .removeHeader("Cache-Control")
                .header("Cache-Control", cacheControl.toString())
                .build();
    }
}

```

https://square.github.io/okhttp/features/caching/

2023-04-28 11:40 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/QuadPayPaymentWidget.java
> +                        if(tierAmount <= Float.parseFloat(amount)){
In the example some of the payment widgets don't pass in an amount, and I get an exception thrown here.  Can we put in something to deal with this?  Maybe default the amount to 0 if not received?

2023-04-28 13:04 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/QuadPayWidgetTextView.java
> +    private String widget_text = null;
Done

2023-04-28 13:09 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/QuadPayPaymentWidget.java
> +                        if(tierAmount <= Float.parseFloat(amount)){
Done

2023-05-05 12:10 UTC, rhyswilliamszip requested changes
Yo,

Appreciate there is quite allot of comments here.  But really looking to resolve what the IDE is telling us.  There are other changes in files not here but think we will do it one step at a time.

Making the amount in the `Timelapse` to a float is going to cause issues in `RNQuadPayPaymentWidget`.  A quick fix would be to create a method to try and parse the amount to pass into the timelapse

```
public float getAmount(){
        if(this.amount != null && !this.amount.equals("")){
            try{
                return Float.parseFloat(this.amount);
            } catch(Exception e){
                return 0;
            }
        }

        return 0;
    }
```

2023-05-09 09:27 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/QuadPayPaymentWidget.java
> +    private String hideTimelineText = null;
Done

2023-05-09 10:07 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/QuadPayPaymentWidget.java
> +import com.quadpay.quadpay.Network.MerchantConfigResult;
Done

2023-05-09 10:22 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/QuadPayWidgetTextView.java
> +            public void onResponse(Call<WidgetData> call , Response<WidgetData> response){
Done

2023-05-09 13:02 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/QuadPayPaymentWidget.java
> +                if (feeTiers != null) {
Done

2023-05-09 13:13 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/QuadPayPaymentWidget.java
> +                WidgetData widgetData = response.body();
Done

2023-05-09 13:13 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/QuadPayPaymentWidget.java
> +                    amount = String.valueOf((Float.parseFloat(amount) + maxFee));
Done

2023-05-09 13:14 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/QuadPayPaymentWidget.java
> +        if (merchantId != null) {
Done

2023-05-09 13:15 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/QuadPayWidgetTextView.java
> +                WidgetData widgetData= response.body();
Done

2023-05-09 13:16 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/Network/GatewayClient.java
> +    private GatewayApi gatewayApi;
Done

2023-05-09 13:16 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/Network/MerchantConfigClient.java
>      private MerchantConfigApi merchantConfigApi;
Done

2023-05-09 13:18 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/FeeTierText.java
> +    private SpannableStringBuilder sb = new SpannableStringBuilder();
Done

2023-05-09 13:19 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/PaymentWidgetSubtitle.java
>      private SpannableStringBuilder sb = new SpannableStringBuilder();
Done

2023-05-09 20:03 UTC, rhyswilliamszip commented
One other key point is the `insertModal` function needs to have the `showTilaTerm` option added in to the `webbank-feature-branch`, and this option needs to be set in your index.html file if `BankPartner` is WebBank.

2023-05-16 08:36 UTC, rhyswilliamszip requested changes
Quick question as well, why do we have two `RNQuadPayWidget` components?  One in the `RNComponents` folder and another in the root?

2023-05-16 08:36 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/Network/WidgetData.java
> +import java.util.List;
Remove unused import.

2023-05-16 08:36 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/FeeTierText.java
> +            sb.append("There may be a $")
Can we define constants at the top of this class so we don't define the text twice?  i.e.

```
private static final String PRE_FEE_TEXT = "There may be a $";
private static final String POST_FEE_TEXT = " finance charge to use Zip. This charge is included above.";
```

2023-05-16 08:36 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/PaymentWidgetHeader.java
> +    private void PaymentWidgetWithOutMerchant(VerticalImageSpan imageSpanInfo, String merchantId, String learnMoreUrl, String isMFPPMerchant, String minModal, String hasFees) {
Can we rename this method to something more meaningful, like `PaymentWidgetTitle`

2023-05-16 08:36 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/PaymentWidgetHeader.java
>          Drawable info = ContextCompat.getDrawable(context,R.drawable.info);
My IDE indicates we need a null check here.

```
if (info == null){
    return;
}
```

2023-05-16 08:36 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/QuadPayPaymentWidget.java
> +    private String hasFees;
Indicates this can be turned into a local variable as it's only used once in `setLayout`

2023-05-16 08:36 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/QuadPayPaymentWidget.java
> +    private Boolean applyFee = false;
Is `applyFee` needed?  Looks like we can just use `maxFee` and check if non-zero.

2023-05-16 08:36 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/QuadPayInfoSpan.java
> +    public QuadPayInfoSpan(String url, String merchantId, String learnMoreUrl, String isMFPPMerchant, String minModal, String hasFees) {
Given `hasFees` is a new field, can we not use a `boolean` as it should be?  It's not like it will break existing functionality.  We should be using the correct data types.

2023-05-16 08:36 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/QuadPayWidgetTextView.java
> +    private String hasFees;
Should be a `boolean`

2023-05-16 08:36 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/QuadPayWidgetTextView.java
> +            public void onResponse(Call<WidgetData> call , Response<WidgetData> response){
Just checked but this is still outstanding...

2023-05-16 08:36 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/QuadPayWidgetTextView.java
> +                feeTiers = widgetData.getFeeTierList();
If we have the `feeTiers` here we can work out the `maxFee`?  E.g. put the code below

```
if(feeTiers!=null && amount != null) {
    for(WidgetData.FeeTier feeTier : feeTiers){
        float tierAmount = feeTier.getFeeStartsAt();
        if(tierAmount <= Float.parseFloat(amount)){
            if(maxTier < tierAmount){
                maxTier = tierAmount;
                maxFee = feeTier.getTotalFeePerOrder();
            }
        }
    }
}
```
That way the code can be removed from the `SetAmount` method.

2023-05-16 08:36 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/RNComponents/RNQuadPayPaymentWidget.java
> +                        "false"
Why is `hasFees` hardcoded here?  Is it because we're going to add in additional code later?  The `RNQuadPayPaymentWidget` is the native component react native uses underneath?  It should work the same.

2023-05-16 08:36 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/RNComponents/RNQuadPayWidget.java
> +                    "false"
Same question as other RN component, why is `hasFees` hardcoded?

2023-05-16 10:02 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/RNComponents/RNQuadPayPaymentWidget.java
> +                        "false"
I didnt do the changes for the wrapper yet but i had to set a default value for the time being.

2023-05-16 10:07 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/Network/WidgetData.java
> +import java.util.List;
Done

2023-05-16 10:09 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/FeeTierText.java
> +            sb.append("There may be a $")
Done

2023-05-16 10:11 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/PaymentWidgetHeader.java
> +    private void PaymentWidgetWithOutMerchant(VerticalImageSpan imageSpanInfo, String merchantId, String learnMoreUrl, String isMFPPMerchant, String minModal, String hasFees) {
Done

2023-05-16 10:37 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/QuadPayPaymentWidget.java
> +    private String hasFees;
Done

2023-05-16 10:39 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/QuadPayPaymentWidget.java
> +    private Boolean applyFee = false;
You are right is not needed at all, i think i had it before but then i added the logic for maxFee so i am removing it

2023-05-16 12:34 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/QuadPayWidgetTextView.java
> +            public void onResponse(Call<WidgetData> call , Response<WidgetData> response){
Done

2023-05-16 12:36 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/QuadPayWidgetTextView.java
> +                WidgetData widgetData= response.body();
Done

2023-05-16 12:39 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/QuadPayWidgetTextView.java
> +                feeTiers = widgetData.getFeeTierList();
Done

2023-05-17 11:43 UTC, rhyswilliamszip requested changes

2023-05-17 11:43 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/PaymentWidgetHeader.java
>      private SpannableStringBuilder sb = new SpannableStringBuilder();
Make this `final`

2023-05-17 11:43 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/QuadPayPaymentWidget.java
> +        Boolean hasFees = maxFee != 0f ? true : false;
This can be simplified to `Boolean hasFees = maxFee != 0f;`

2023-05-17 11:43 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/QuadPayWidgetTextView.java
> +                Float maxTier = 0f;
Use primitive float instead of class, so lower case float instead of Float

2023-05-17 11:43 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/QuadPayWidgetTextView.java
> +                hasFees = maxFee != 0f? true : false;
This can be simplified to `hasFees = maxFee != 0f;`

2023-05-17 11:43 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/ZipWidgetActivity.java
> +        Boolean hasFees = intent.getBooleanExtra("hasFees", false);
Use primitive, boolean instead of Boolean

2023-05-18 08:58 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/PaymentWidgetHeader.java
>      private SpannableStringBuilder sb = new SpannableStringBuilder();
Done

2023-05-18 09:00 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/QuadPayWidgetTextView.java
> +                Float maxTier = 0f;
Done

2023-05-18 09:00 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/QuadPayWidgetTextView.java
> +                hasFees = maxFee != 0f? true : false;
Done

2023-05-18 09:03 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/QuadPayPaymentWidget.java
> +        Boolean hasFees = maxFee != 0f ? true : false;
Done

2023-05-18 09:03 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/ZipWidgetActivity.java
> +        Boolean hasFees = intent.getBooleanExtra("hasFees", false);
Done

2023-05-18 16:11 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/QuadPayPaymentWidget.java
> +        Boolean hasFees = maxFee != 0f ? true : false;
This hasn't been done.

2023-05-18 16:18 UTC, rhyswilliamszip approved these changes

2023-05-22 11:17 UTC, rhyswilliamszip approved these changes

2023-05-22 12:19 UTC, rhyswilliamszip requested changes

2023-05-22 12:19 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/Network/WidgetData.java
> +    private String bankPartner;
Similar to iOS can we change the `BankPartner` to an `enum`?

```
public enum BankPartner {
    NONE("None"),
    WEBBANK("WebBank");

    private final String value;

    BankPartner(final String value){
        this.value = value;
    }

    @NonNull
    @Override
    public String toString() {
        return value;
    }
}
```

Can then use `toString` method when actually setting value on `index.html` file.

2023-05-22 19:42 UTC, rhyswilliamszip approved these changes

2023-05-23 09:59 UTC, merged