Petros/cko 1814 create rn component
quadpay/quadpay-merchant-sdk-android pull request #7
Opened 2022-10-19 11:25 UTC by PetrosZip

2022-11-29 20:43 UTC, alex-lane commented on quadpay/build.gradle
> +            buildConfigField "String", "CdnUrl", "\"https://qp-merchant-configs-dev.azureedge.net/\""
These should be production values. Is there a way to keep the values secure in our source repo like the ios repo?

2022-11-29 20:44 UTC, alex-lane commented on quadpay/publish.gradle
> +                    name = "com.quadpay.quadpay-beta"
`-beta`?

2022-11-29 20:44 UTC, alex-lane commented on quadpay/src/main/assets/index.html
> +<!--<html>-->
Do we need this commented out code?

2022-12-01 15:11 UTC, alex-lane commented on quadpay/src/main/res/values/strings.xml
> +    <string name="widget_text_min">4 payments on order over</string>
Should `order` be plural?

2022-12-01 15:11 UTC, alex-lane commented on quadpay/src/main/res/values/urls.xml
> +    <string name="quadpay_url_widget" translatable="false">https://portal.sandbox.afterpay.com/afterpay.js?merchant_key=demo</string>
Afterpay?

2022-12-01 15:11 UTC, alex-lane commented on quadpay/src/main/res/values/urls.xml
> +    <string name="quadpay_cdn" translatable="false">https://qp-merchant-configs-dev.azureedge.net/</string>
Should this be the production value?

2022-12-01 15:12 UTC, alex-lane requested changes
Looking good. Left a few comments.

2022-12-05 14:56 UTC, PetrosZip commented on quadpay/src/main/res/values/urls.xml
> +    <string name="quadpay_cdn" translatable="false">https://qp-merchant-configs-dev.azureedge.net/</string>
need to remove this file since we are getting the value from the config now

2022-12-05 15:37 UTC, PetrosZip commented on quadpay/publish.gradle
> +                    name = "com.quadpay.quadpay-beta"
When i was publishing for testing i am fixing it now

2022-12-07 14:37 UTC, PetrosZip commented on quadpay/build.gradle
> +            buildConfigField "String", "CdnUrl", "\"https://qp-merchant-configs-dev.azureedge.net/\""
This is done

2023-01-11 12:49 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/QuadPayInfoSpan.java
> +    String learnMoreUrl;
Mark these fields as private following best practices and they are not required out with the class.

2023-01-11 12:49 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/QuadPayWebview.java
> +                System.out.println(data);
Assume this print statement can be removed?

2023-01-11 12:49 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/QuadPayWidgetTextView.java
> +            setTextSize(TypedValue.COMPLEX_UNIT_PX, getTextSize() * (size.equals("") ? 100 / 100 : getTextSizeFromAttributes(size)));
Why do 100 / 100 here?  Couldn't you just use 1?

2023-01-11 12:49 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/QuadPayWidgetTextView.java
> +                        Drawable merchantLogo = ContextCompat.getDrawable(context,R.drawable.welcome_pay);
Assume this is still outstanding?  Eventually we'll need to use the image returned from the server?

2023-01-11 12:49 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/RNQuadPayWidget.java
> +    private Drawable grayLabel = ContextCompat.getDrawable(getContext(),R.drawable.welcome_pay);
We still have the hardcoded welcome pay image here?

2023-01-11 15:17 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/RNQuadPayWidget.java
> +    private Drawable grayLabel = ContextCompat.getDrawable(getContext(),R.drawable.welcome_pay);
Yes since getting it from URL is breaking the image.

2023-01-11 15:18 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/QuadPayWidgetTextView.java
> +                        Drawable merchantLogo = ContextCompat.getDrawable(context,R.drawable.welcome_pay);
Yes at the moment getting the svg image from url is breaking the image.

2023-01-11 17:01 UTC, rhyswilliamszip approved these changes

2023-03-07 11:19 UTC, closed without merging