Petros/widgets
quadpay/quadpay-merchant-sdk-android pull request #9
Opened 2023-03-07 11:16 UTC by PetrosZip

2023-03-08 12:55 UTC, rhyswilliamszip requested changes
Can we refactor the structure so that we have a `Widgets` folder with a folder for the standard widget and payments widget.

Would also be good to move utils functions such as the UrlBuilder into a separate folder.

`MerchantConfigApi` etc. could go into a network folder.

2023-03-08 12:55 UTC, rhyswilliamszip commented on example/src/main/java/com/quadpay/sdkexample/ui/home/HomeFragment.java
> +        details.checkoutFlow = "express";
Would be good to add these fields to a UI in the future, so users can dynamically test different data being passed in, especially different flows such as standard or express.

2023-03-08 12:55 UTC, rhyswilliamszip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/Timelapse.java
> +                paint.setColor(Color.parseColor("#AA8FFF"));
You're passing in the color, so why not pass in the hex value and use it directly instead of hardcoding?

2023-03-09 15:21 UTC, PetrosZip commented on example/src/main/java/com/quadpay/sdkexample/ui/home/HomeFragment.java
> +        details.checkoutFlow = "express";
that is already there for standard and express

2023-03-09 15:22 UTC, PetrosZip commented on quadpay/src/main/java/com/quadpay/quadpay/PaymentWidget/Timelapse.java
> +                paint.setColor(Color.parseColor("#AA8FFF"));
because for payment widget the merchant can pass only black anything else will go to default zip color

2023-03-09 15:46 UTC, rhyswilliamszip approved these changes

2023-03-09 16:01 UTC, merged